name: TimGrimes.com
favicon: null
layout_spectrum: 0.9097572634927928
typography_spectrum: 0.8280858534853905
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7453047179151326
  lightness: 0.10313426051288843
  saturation: 0.7782308619935066
  rhythmicContrast: 0.6028790650889277
purpose: []
